name = "code"
main = ".open-next/worker.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXTAUTH_URL = "https://code.tardis.digital"


[[d1_databases]]
binding = "DB"
database_name = "devflow-db"
database_id = "f31399e8-8e40-457f-86e8-669e46091e29"

[[kv_namespaces]]
binding = "USER_KEYS"
id = "ec28be3e6c0d408babe6d0b764cf8f67"